import fs from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const read = async (file) => JSON.parse(await fs.readFile(file, "utf8"));
const files = (await fs.readdir("content/products")).filter((f) =>
  f.endsWith(".json"),
);
const records = [];
for (const file of files) {
  const p = await read(`content/products/${file}`);
  if (!p.published) continue;
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug) || file !== `${p.slug}.json`)
    throw new Error(`Invalid product route: ${file}`);
  for (const field of [
    "name",
    "strength",
    "form",
    "category",
    "tag",
    "context",
    "caution",
    "note",
    "packUnit",
    "preparation",
  ])
    if (typeof p[field] !== "string" || !p[field].trim())
      throw new Error(`Missing ${field}: ${file}`);
  if (!Number.isInteger(p.pack) || p.pack < 1)
    throw new Error(`Invalid pack: ${file}`);
  if (!p.ka?.name || !p.ka.context || !p.ka.caution || !p.ka.note)
    throw new Error(`Incomplete Georgian content: ${file}`);
  if (!Array.isArray(p.refs) || !p.refs.length)
    throw new Error(`Missing references: ${file}`);
  for (const key of ["specialty", "use", "system"])
    if (
      !p.facets?.[key]?.length ||
      p.facets[key].length !== p.ka?.facets?.[key]?.length
    )
      throw new Error(`Incomplete bilingual ${key}: ${file}`);
  if (
    !/^\/(products|uploads)\/[a-zA-Z0-9_./-]+\.(png|jpe?g|webp)$/i.test(
      p.image,
    ) ||
    p.image.includes("..")
  )
    throw new Error(`Invalid product image: ${file}`);
  const meta = await sharp(path.join("public", p.image)).metadata();
  p.imageWidth = meta.width;
  p.imageHeight = meta.height;
  p.originalImage = p.image;
  p.image = p.image.replace(/\.(png|jpe?g)$/i, ".webp");
  records.push(p);
}
records.sort(
  (a, b) => (a.order ?? 999) - (b.order ?? 999) || a.slug.localeCompare(b.slug),
);
const sourceList = (await read("content/sources.json")).sources;
if (new Set(sourceList.map((s) => s.id)).size !== sourceList.length)
  throw new Error("Duplicate clinical source IDs");
for (const s of sourceList)
  if (!s.id || !s.title || !s.titleKa || !s.url.startsWith("https://"))
    throw new Error("Incomplete clinical source");
const sources = Object.fromEntries(sourceList.map(({ id, ...s }) => [id, s]));
const allowed = new Set([
  "www.accessdata.fda.gov",
  "www.ema.europa.eu",
  "jamanetwork.com",
  "pmc.ncbi.nlm.nih.gov",
  "www.fda.gov",
]);
for (const p of records)
  for (const id of p.refs)
    if (!sources[id] || !allowed.has(new URL(sources[id].url).hostname))
      throw new Error(`Unrecognized clinical source for ${p.slug}: ${id}`);
const copy = await read("content/copy.json");
const home = await read("content/home.json");
if (new Set(copy.entries.map((e) => e.key)).size !== copy.entries.length)
  throw new Error("Duplicate website text keys");
for (const e of copy.entries)
  if (
    typeof e.key !== "string" ||
    typeof e.en !== "string" ||
    typeof e.ka !== "string"
  )
    throw new Error("Invalid bilingual website text");
for (const section of home.sections || []) {
  if (!section.published) continue;
  if (
    !["/", "/about", "/compounding", "/contact", "/products"].includes(
      section.page,
    )
  )
    throw new Error("Invalid extra section destination");
  for (const lang of ["en", "ka"])
    for (const field of ["title", "body"])
      if (!section[lang]?.[field]?.trim())
        throw new Error("Incomplete bilingual content section");
  if (section.image) {
    if (
      !/^\/(products|uploads)\/[a-zA-Z0-9_./-]+\.(png|jpe?g|webp)$/i.test(
        section.image,
      ) ||
      section.image.includes("..")
    )
      throw new Error("Invalid section image");
    await sharp(path.join("public", section.image)).metadata();
  }
}
await fs.writeFile(
  "src/generated-content.js",
  `// Generated from the authenticated CMS content. Do not edit this file.\nexport const records=${JSON.stringify(records)};\nexport const sourceRecords=${JSON.stringify(sources)};\nexport const siteCopy=${JSON.stringify(copy.entries)};\nexport const extraSections=${JSON.stringify((home.sections || []).filter((s) => s.published))};\n`,
);
console.log(
  `Generated ${records.length} published products and bilingual site content.`,
);
